bq_louisville_data:
  outputs:
    dev:
      dataset: louisville_data_all
      fixed_retries: 1
      keyfile: /root/.google/credentials/google_credentials.json
      location: europe-west6
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 1
      timeout_seconds: 300
      type: bigquery
  target: dev